config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :genres
  resources :notifications

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get "/fetch_movies" => 'movies#from_genre', as: 'fetch_movies'

  resources :subscribers
  get "/subscribe" => 'subscribers#subscribe', as: 'subscribe'
  get "/unsubscribe" => 'subscribers#unsubscribe', as: 'unsubscribe'

  post '/rate' => 'rater#create', :as => 'rate'
  
  devise_for :users

  resources :movies do
    resources :comments
    collection { post :search, to: 'movies#index'}
  end
  
  resources :comments do
    resources :comments
  end
  
  resources :directors

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  root 'movies#index'

  

end

app/models/genre.rb
class Genre < ActiveRecord::Base
  before_destroy :remove_image_file
  
  has_and_belongs_to_many :movies
  has_many :subscribers
  has_many :notifications
  
  mount_uploaders :images, ImageUploader
  serialize :images, JSON
    
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  validates :name, presence: true, uniqueness: true
  
  def remove_image_file
    FileUtils.rm_rf("#{Rails.root}/public/uploads/genre/images/#{self.id}")
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create,:update,:destroy]
  before_action :set_genre
  load_and_authorize_resource
  expose :genres,-> {Genre.all}

  def index
  end

  def show
  end

  def new
    @genre = Genre.new
  end

  def edit
  end

  def create
    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: genre.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def genre_params
      params.require(:genre).permit(:name, images: [])
    end

    def set_genre
      @genre = Genre.find_by_slug(params[:id])
    end
end

app/helpers/genres_helper.rb
module GenresHelper
  def sub_genre_exist(user_id, genre_id)
    relationship = Subscriber.find_by(user_id: user_id, genre_id: genre_id)
    return true if relationship
  end
end

app/views/genres/_form.html.haml
= form_for(@genre) do |f|
  - if @genre.errors.any?
    #error_explanation
      %h2
        = pluralize(@genre.errors.count, "error")
        prohibited this genre from being saved:
      %ul
        - @genre.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.file_field :images, multiple: true, accept: "image/jpeg, image/jpg, image/gif, image/png"
  .actions
    = f.submit

app/views/genres/_genre_row.html.haml
%div.movie
	%div.cover= image_tag(genre.images.first.url) if genre.images.first.present?
	%span.title=  genre.name
	%span{style:"float:right"}
		- if user_signed_in?
			- if !sub_genre_exist(current_user.id, genre.id)
				= link_to "Subscribe", subscribe_path(genre_id: genre.id), class:"btn btn-primary"
			- else
				= link_to 'Unsubscribe', unsubscribe_path(genre_id: genre.id), class:'btn btn-primary'
	- if can? :delete, Genre
		%p= link_to 'Destroy', genre, method: :delete, data: { confirm: 'Are you sure?' }
	- if can? :edit, Genre
		%p= link_to 'Edit', edit_genre_path(genre)

app/views/genres/edit.html.haml
%h1 Editing Genre
= render 'form'
= link_to 'Show', @genre
|
= link_to 'Back', genres_path

app/views/genres/index.html.haml
.top-bar
.movies.flex-container
	- genres.each do |genre|
		= render 'genre_row', genre: genre
	-if can? :create, Genre
		=link_to 'Create Genre', new_genre_path

app/views/genres/new.html.haml
%h1 New Genre
= render 'form'
= link_to 'Back', genres_path

app/views/genres/show.html.haml
%p#notice= notice
%p
  %strong Name:
  = @genre.name
= link_to 'Edit', edit_genre_path(@genre)
|
= link_to 'Back', genres_path