config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :genres
  resources :notifications

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get "/fetch_movies" => 'movies#from_genre', as: 'fetch_movies'

  resources :subscribers
  get "/subscribe" => 'subscribers#subscribe', as: 'subscribe'
  get "/unsubscribe" => 'subscribers#unsubscribe', as: 'unsubscribe'

  post '/rate' => 'rater#create', :as => 'rate'
  
  devise_for :users

  resources :movies do
    resources :comments
    collection { post :search, to: 'movies#index'}
  end
  
  resources :comments do
    resources :comments
  end
  
  resources :directors

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  root 'movies#index'

  

end

app/models/director.rb
class Director < ActiveRecord::Base
    before_destroy :remove_image_file
    before_validation :create_slug

    mount_uploaders :images, ImageUploader
    serialize :images, JSON
        
    has_many :movies
    has_many :subscribers
    has_many :notifications
    
    ratyrate_rateable 'director_rating'
    
    validates_presence_of :firstname, :lastname, :year_of_birth

    extend FriendlyId
    friendly_id :slug, use: :slugged
    
    def fullname
      self.firstname + " " + self.lastname
    end

    def slug
      "#{self.firstname}-#{self.lastname}".downcase
    end

    def create_slug
      self.slug = slug
    end
    
    def remove_image_file
      FileUtils.rm_rf("#{Rails.root}/public/uploads/director/images/#{self.id}")
    end
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  before_action :authenticate_user!, only: [:new,:create,:update,:destroy]
  load_and_authorize_resource
  expose :directors, ->{ Director.all }

  def index
  end

  def show
    binding.pry
  end

  def new
    @director = Director.new
  end

  def edit
  end

  def create
    respond_to do |format|
      if @director.save
        format.html { redirect_to director, notice: 'Director was successfully created.' }
        format.json { render :show, status: :created, location: director }
      else
        format.html { render :new }
        format.json { render json: director.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @director.update(director_params)
        format.html { redirect_to director, notice: 'Director was successfully updated.' }
        format.json { render :show, status: :ok, location: director }
      else
        format.html { render :edit }
        format.json { render json: director.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @director.destroy
    respond_to do |format|
      format.html { redirect_to directors_url, notice: 'Director was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
  
  def director_params
    params.require(:director).permit(:firstname,:lastname,:year_of_birth, images: [])
  end

  def set_director
    @director = Director.find_by_slug(params[:id])
  end
end

app/helpers/directors_helper.rb
module DirectorsHelper
  def sub_director_exist(user_id, director_id)
    relationship = Subscriber.find_by(user_id: user_id, director_id: director_id)
    return true if relationship
  end
end

app/views/directors/_director_row.html.haml
%div.movie
  %div.cover= link_to image_tag(director.images.first.url), director if director.images.first.present?
  - if action_name == "index"
    %div.title= link_to director.fullname, director

app/views/directors/_form.html.haml
= form_for( director) do |f|
  - if director.errors.any?
    #error_explanation
      %h2
        = pluralize(director.errors.count, "error")
        prohibited this director from being saved:
      %ul
        - @director.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :firstname
    %br/
    = f.text_field :firstname
  .field
    = f.label :lastname
    %br/
    = f.text_field :lastname
  .field
    = f.label :year_of_birth
    %br/
    = f.number_field :year_of_birth
  .field
    = f.label :images
    %br/
    = f.file_field :images, multiple: true, accept: "image/jpeg, image/jpg, image/gif, image/png"
  .actions
    = f.submit

app/views/directors/edit.html.haml
%h1 Editing Director
= render 'form'
= link_to 'Show', director
|
= link_to 'Back', directors_path

app/views/directors/index.html.haml
%div.top-bar
%div.movies.flex-container
  - directors.each do |director|
    = render 'director_row', director: director

app/views/directors/new.html.haml
%h1 New Director
= render 'form'
= link_to 'Back', directors_path

app/views/directors/show.html.haml
%div.movie-show-page
  %div.top-bar
  %div.movie-show
    %div.movie-cover.col-lg-3
      = image_tag(@director.images.first.url, alt: "#{@director.fullname} Cover") if @director.images.present?
    
    %div.movie-info.col-lg-9
      %span.title= director.fullname
      %ul
        - if !sub_director_exist(current_user.id, @director.id)
          %li.subscribe.btn.btn-primary= link_to 'Subscribe', subscribe_path(director_id: @director.id)
        - else
          %li.unsubscribe.btn.btn-primary= link_to 'Unsubscribe', unsubscribe_path(director_id: @director.id)
      -if user_signed_in?
        %span.rating= rating_for @director, 'director_rating', cancel_place: 'right'

      %div.movie-controls
        - if can? :delete, Director
          =link_to 'Destroy', director, method: :delete, data: { confirm: 'Are you sure?' }
        - if can? :edit, Director
          =link_to 'Edit', edit_director_path(director)

    %div.col-lg-12.filmography
      %h2 Filmography
      %br
      %div.flex-container
        - @director.movies.each do |movie|
          = render 'movies/movie_row', movie: movie