config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :genres
  resources :notifications

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get "/fetch_movies" => 'movies#from_genre', as: 'fetch_movies'

  resources :subscribers
  get "/subscribe" => 'subscribers#subscribe', as: 'subscribe'
  get "/unsubscribe" => 'subscribers#unsubscribe', as: 'unsubscribe'

  post '/rate' => 'rater#create', :as => 'rate'
  
  devise_for :users

  resources :movies do
    resources :comments
    collection { post :search, to: 'movies#index'}
  end
  
  resources :comments do
    resources :comments
  end
  
  resources :directors

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  root 'movies#index'

  

end

app/models/notification.rb
class Notification < ActiveRecord::Base
  scope :after_sub, -> (sub_date) { where("created_at > ?",sub_date) }
  scope :unread, -> { where(read: false) }
  
  belongs_to :user
  belongs_to :director
  belongs_to :movie
  belongs_to :genre
  belongs_to :comment

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
<<<<<<< HEAD

=======
  
>>>>>>> a1d9525de1485bad64f54127a47f7dd3ce2fc7e8
  def index
    @notifications,@allnotifications = Notifications::ListNotifications.new(current_user).call
  end
  
  def link_through
    notification = Notification.find(params[:id])
    if notification.update(read: true)
      redirect_to movie_path(notification.movie)
    end
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
    def notifications_number
      subbed = current_user.subscribers
     
      notifications = []
      comments_notification = Notification.where("comment_id is not ? AND user_id =?",nil,current_user.id).unread
      
      if subbed.any?
        sub_date = subbed.last.created_at
        subbed_dir = subbed.pluck(:director_id).compact
        subbed_genre = subbed.pluck(:genre_id).compact
        
        dir_notif = Notification.where(director_id: subbed_dir).unread
        genre_notif = Notification.where(genre_id: subbed_genre).unread
        
        notifications = dir_notif.after_sub(sub_date) + genre_notif.after_sub(sub_date)
      end
      
      notifications += comments_notification        
      if notifications.size>0
        return notifications.size
      end
    end
end

app/views/notifications/index.html.haml
%div.top-bar
%div.container
  - if @allnotifications.try(:any?)
    %h1 New Notifications
  
    - @notifications.each do |n|
      - if n.director
        %li=link_to "There is a #{n.notification_type} with title #{n.movie.title} created by #{n.director.fullname}", link_through_path(n)
      - elsif n.genre
        %li=link_to "There is a #{n.notification_type} with title #{n.movie.title} and genre #{n.genre.name}", link_through_path(n)
      - elsif n.comment
        %li=link_to "User with email #{n.comment.user.email} commented your post", link_through_path(n)
        
    %h1 Old Notifications
    
    - @allnotifications.each do |n|
      - if n.director
        %li=link_to "There is a #{n.notification_type} with title #{n.movie.title} created by #{n.director.fullname}", movie_path(n.movie)
      - elsif n.genre
        %li=link_to "There is a #{n.notification_type} with title #{n.movie.title} and genre #{n.genre.name}", movie_path(n.movie)
        
  - else
    %h1 You don't have any notifications