config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :genres
  resources :notifications

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get "/fetch_movies" => 'movies#from_genre', as: 'fetch_movies'

  resources :subscribers
  get "/subscribe" => 'subscribers#subscribe', as: 'subscribe'
  get "/unsubscribe" => 'subscribers#unsubscribe', as: 'unsubscribe'

  post '/rate' => 'rater#create', :as => 'rate'
  
  devise_for :users

  resources :movies do
    resources :comments
    collection { post :search, to: 'movies#index'}
  end
  
  resources :comments do
    resources :comments
  end
  
  resources :directors

  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]

  root 'movies#index'

  

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    if user.has_role? :admin
      can :manage, :all
    else
      if user.has_role? :moderator
        can :manage, [Movie,Director,Comment, Genre]
      end
      if user.has_role? :user
        can :manage, [OrderItem, Subscriber]
      end
      
      can :read, [Movie,Director,Comment, Genre]
    end
    
    
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :commentable, polymorphic: true
    has_many :comments, as: :commentable
    belongs_to :user
    has_many :notifications
    belongs_to :movie
end

app/models/director.rb
class Director < ActiveRecord::Base
    before_destroy :remove_image_file
    before_validation :create_slug

    mount_uploaders :images, ImageUploader
    serialize :images, JSON
        
    has_many :movies
    has_many :subscribers
    has_many :notifications
    
    ratyrate_rateable 'director_rating'
    
    validates_presence_of :firstname, :lastname, :year_of_birth

    extend FriendlyId
    friendly_id :slug, use: :slugged
    
    def fullname
      self.firstname + " " + self.lastname
    end

    def slug
      "#{self.firstname}-#{self.lastname}".downcase
    end

    def create_slug
      self.slug = slug
    end
    
    def remove_image_file
      FileUtils.rm_rf("#{Rails.root}/public/uploads/director/images/#{self.id}")
    end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  before_destroy :remove_image_file
  
  has_and_belongs_to_many :movies
  has_many :subscribers
  has_many :notifications
  
  mount_uploaders :images, ImageUploader
  serialize :images, JSON
    
  extend FriendlyId
  friendly_id :name, use: :slugged
  
  validates :name, presence: true, uniqueness: true
  
  def remove_image_file
    FileUtils.rm_rf("#{Rails.root}/public/uploads/genre/images/#{self.id}")
  end
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  def email
      "Guest"
  end
  
  def method_missing(name, *args, &block)
    self
  end
  
  def has_role?(role)
    false
  end
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  before_destroy :remove_image_file

  paginates_per 20
      
  mount_uploaders :images, ImageUploader
  mount_uploaders :covers, CoverUploader
  serialize :images, JSON
  serialize :covers, JSON

  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  ratyrate_rateable 'rating'

  belongs_to :director
  accepts_nested_attributes_for :director, allow_destroy: true
  has_many :order_items, dependent: :destroy
  has_many :comments, as: :commentable
  has_many :notifications, dependent: :destroy
  has_and_belongs_to_many :genres
  
  validates :title, presence: true, uniqueness: true
  validates_presence_of :desc, :year, :time, :price
  
  def remove_image_file
    FileUtils.rm_rf("#{Rails.root}/public/uploads/movie/images/#{self.id}")
    FileUtils.rm_rf("#{Rails.root}/public/uploads/movie/covers/#{self.id}")
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  scope :after_sub, -> (sub_date) { where("created_at > ?",sub_date) }
  scope :unread, -> { where(read: false) }
  
  belongs_to :user
  belongs_to :director
  belongs_to :movie
  belongs_to :genre
  belongs_to :comment

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_items

  def total
    order_items.collect { |oi| oi.valid? ? (oi.unit_price) : 0 }.sum
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :movie
  belongs_to :order
  
  before_save :finalize
  
  def unit_price
    if persisted?
      self[:unit_price]
    else 
      movie.price
    end
  end
  
  def total_price
    unit_price
  end
  
private

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = total_price
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
    has_many :orders
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true
          
  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true
  scopify
end

app/models/subscribed.rb
class Subscribed < ActiveRecord::Base
  belongs_to :user
  belongs_to :director
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  belongs_to :user
  belongs_to :director
  belongs_to :genre
  
  validates_presence_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  after_create :assign_default_role
  
  has_many :subscribers
  has_many :notifications
  has_many :comments
  
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  ratyrate_rater
  
  validates :email, presence: true, uniqueness: true

  def method_missing(name, *args, &block)
    self
  end

  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
  def sub_genre_exist(user_id, genre_id)
    relationship = Subscriber.find_by(user_id: user_id, genre_id: genre_id)
    return true if relationship
  end
end

app/views/layouts/_cart_text.html.haml
= link_to "#{current_order.order_items.size} Items in Cart ( #{number_to_currency current_order.total} )", cart_path, class: "btn btn-link"

app/views/layouts/_menu.html.haml
%div.menu
  %ul
    %li.divider User Settings
    -if user_signed_in? 
      %li Hello #{current_user.email}
      %li= link_to 'My Account', edit_user_registration_path
      %li= link_to "Sign out", destroy_user_session_path, :method => :delete
    -else 
      %li= link_to 'Sign in', new_user_session_path
      %li= link_to 'Sign up', new_user_registration_path
    -if user_signed_in?
      %li= link_to "Subscribers", subscribers_path
      %li= link_to "Notifications", notifications_path
    %li.divider Tables
    %li= link_to "Genres", genres_path
    %li= link_to "Directors", directors_path
    - if controller_name == "movies"
      %li.divider Genres
      - genres.each do |g|
        %li= link_to g.name, fetch_movies_path(:genre_ids => g.id), remote: true

app/views/layouts/_navbar.html.haml
%div#navbar
  %div.left-side
    %div.menu-icon
      %div#nav-icon
        %span
        %span
        %span
    
    = link_to root_path do
      %div.logo
  
  -if user_signed_in?  
    %div.right-side
      =link_to notifications_path, class:"fa fa-bell",id:"notif-bell", aria: {hidden: true} do
        -if notifications_number
          %span.notif-counter= notifications_number
      %div.cart
        %span.cart-text= render 'layouts/cart_text'
      %div.search-form
        = search_form_for @search, url: search_movies_path, method: :post do |f|
          = f.search_field :title_cont
          = button_tag do
            %i.fa.fa-search

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Movie site
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    - if request.ssl?
      = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'
      = javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js'
    - else
      = stylesheet_link_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'
      = javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Montserrat',  media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .menu
      = render 'layouts/menu'
    .content
      = render 'layouts/navbar'
      = yield